// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: events.proto

package accountv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PollEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SinceVersion  uint64                 `protobuf:"varint,1,opt,name=since_version,json=sinceVersion,proto3" json:"since_version,omitempty"` // return events with version > this
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                                   // max events per page (server-capped at 1000)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollEventsRequest) Reset() {
	*x = PollEventsRequest{}
	mi := &file_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollEventsRequest) ProtoMessage() {}

func (x *PollEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollEventsRequest.ProtoReflect.Descriptor instead.
func (*PollEventsRequest) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

func (x *PollEventsRequest) GetSinceVersion() uint64 {
	if x != nil {
		return x.SinceVersion
	}
	return 0
}

func (x *PollEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PollEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*InvalidationEvent   `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	MaxVersion    uint64                 `protobuf:"varint,2,opt,name=max_version,json=maxVersion,proto3" json:"max_version,omitempty"` // highest version in stream; use as next since_version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollEventsResponse) Reset() {
	*x = PollEventsResponse{}
	mi := &file_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollEventsResponse) ProtoMessage() {}

func (x *PollEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollEventsResponse.ProtoReflect.Descriptor instead.
func (*PollEventsResponse) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{1}
}

func (x *PollEventsResponse) GetEvents() []*InvalidationEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *PollEventsResponse) GetMaxVersion() uint64 {
	if x != nil {
		return x.MaxVersion
	}
	return 0
}

type InvalidationEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"` // stable ID for dedup
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`                      // account_banned | account_unbanned | link_unlinked | account_delete_started | account_deleted | credential_revoked | friend_requested | friend_accepted | friend_removed (account = who must hear it, subject = the other party)
	AccountId     string                 `protobuf:"bytes,4,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Namespace     string                 `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`                  // set when scoped to one adapter link
	SubjectId     string                 `protobuf:"bytes,6,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"` // set when scoped to one adapter link
	CreatedAtUnix int64                  `protobuf:"varint,7,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidationEvent) Reset() {
	*x = InvalidationEvent{}
	mi := &file_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidationEvent) ProtoMessage() {}

func (x *InvalidationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidationEvent.ProtoReflect.Descriptor instead.
func (*InvalidationEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{2}
}

func (x *InvalidationEvent) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *InvalidationEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *InvalidationEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InvalidationEvent) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *InvalidationEvent) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *InvalidationEvent) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *InvalidationEvent) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

var File_events_proto protoreflect.FileDescriptor

const file_events_proto_rawDesc = "" +
	"\n" +
	"\fevents.proto\x12\x12openpak.account.v1\"N\n" +
	"\x11PollEventsRequest\x12#\n" +
	"\rsince_version\x18\x01 \x01(\x04R\fsinceVersion\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"t\n" +
	"\x12PollEventsResponse\x12=\n" +
	"\x06events\x18\x01 \x03(\v2%.openpak.account.v1.InvalidationEventR\x06events\x12\x1f\n" +
	"\vmax_version\x18\x02 \x01(\x04R\n" +
	"maxVersion\"\xe0\x01\n" +
	"\x11InvalidationEvent\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"account_id\x18\x04 \x01(\tR\taccountId\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x06 \x01(\tR\tsubjectId\x12&\n" +
	"\x0fcreated_at_unix\x18\a \x01(\x03R\rcreatedAtUnix2e\n" +
	"\x06Events\x12[\n" +
	"\n" +
	"PollEvents\x12%.openpak.account.v1.PollEventsRequest\x1a&.openpak.account.v1.PollEventsResponseB%Z#wwfc/corebridge/accountpb;accountv1b\x06proto3"

var (
	file_events_proto_rawDescOnce sync.Once
	file_events_proto_rawDescData []byte
)

func file_events_proto_rawDescGZIP() []byte {
	file_events_proto_rawDescOnce.Do(func() {
		file_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)))
	})
	return file_events_proto_rawDescData
}

var file_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_events_proto_goTypes = []any{
	(*PollEventsRequest)(nil),  // 0: openpak.account.v1.PollEventsRequest
	(*PollEventsResponse)(nil), // 1: openpak.account.v1.PollEventsResponse
	(*InvalidationEvent)(nil),  // 2: openpak.account.v1.InvalidationEvent
}
var file_events_proto_depIdxs = []int32{
	2, // 0: openpak.account.v1.PollEventsResponse.events:type_name -> openpak.account.v1.InvalidationEvent
	0, // 1: openpak.account.v1.Events.PollEvents:input_type -> openpak.account.v1.PollEventsRequest
	1, // 2: openpak.account.v1.Events.PollEvents:output_type -> openpak.account.v1.PollEventsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_events_proto_init() }
func file_events_proto_init() {
	if File_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_events_proto_goTypes,
		DependencyIndexes: file_events_proto_depIdxs,
		MessageInfos:      file_events_proto_msgTypes,
	}.Build()
	File_events_proto = out.File
	file_events_proto_goTypes = nil
	file_events_proto_depIdxs = nil
}
